import org.junit.Test;
import static org.junit.Assert.*;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.PrintStream;

import org.junit.After;
import org.junit.Before;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'xmartijanicolas' at '12/10/16 11:59' with Gradle 2.14.1
 *
 * @author xmartijanicolas, @date 12/10/16 11:59
 */
public class LibraryTest {
   
    private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
   
    @Before
    public void setUpStreams() {
        System.setOut(new PrintStream(outContent));
    }

    @After
    public void cleanUpStreams() {
        System.setOut(null);
    }


    @Test
    public void out() throws IOException {
    	String[] array = new String[1];
    	ClassLoader classLoader = getClass().getClassLoader();
    	File file = new File(classLoader.getResource("afile").getFile());
    	array[0]=file.getPath();
    	Main.main(array);
        assertEquals("1 2 F 4 B F 7 8 F B\r\n1 F 3 F 5 F B F 9 F 11 F 13 FB 15\r\n", outContent.toString());
    }

   
}
